{
  "schemaVersion": "1.0",
  "kind": "agentlas-auto-activation",
  "state": "seed",
  "activationPolicy": {
    "explicitActivation": true,
    "repeatedUseThreshold": 1,
    "mergeOnly": true,
    "neverOverwriteWithoutApproval": true
  },
  "seedFiles": [
    ".agentlas/project-soul-memory.md",
    ".agentlas/sitemap.json",
    ".agentlas/memory-map.json",
    ".agentlas/memory-tickets.jsonl",
    ".agentlas/vault-references.json",
    ".agentlas/skill-registry.json",
    ".agentlas/skill-trials.jsonl",
    ".agentlas/curator-decisions.jsonl",
    ".agentlas/super-ontology-contract.json",
    ".agentlas/super-ontology-open-world-coverage.json",
    ".agentlas/super-ontology-consensus-coordination.json",
    ".agentlas/super-ontology-task-coverage.json",
    ".agentlas/super-ontology-contextual-flow.json",
    ".agentlas/super-ontology-causal-impact.json",
    ".agentlas/super-ontology-assurance-case.json",
    ".agentlas/super-ontology-knowledge-homeostasis.json",
    ".agentlas/super-ontology-adversarial-provenance.json",
    ".agentlas/super-ontology-epistemic-calibration.json",
    ".agentlas/super-ontology-semantic-alignment.json",
    ".agentlas/super-ontology-resilience-control.json",
    ".agentlas/super-ontology-invariant-verification.json",
    ".agentlas/super-ontology-observability-telemetry.json",
    ".agentlas/super-ontology-objective-proxy-validity.json",
    ".agentlas/super-ontology-stakeholder-preference-governance.json",
    ".agentlas/super-ontology-normative-authority-drift.json",
    ".agentlas/super-ontology-side-effect-containment.json",
    ".agentlas/super-ontology-source-lineage-version.json",
    ".agentlas/super-ontology-entity-identity-resolution.json",
    ".agentlas/super-ontology-temporal-state-transition.json",
    ".agentlas/super-ontology-capability-delegation-authority.json",
    ".agentlas/super-ontology-replays.jsonl",
    ".agentlas/super-ontology-evidence.jsonl",
    ".agentlas/super-ontology-memory-bridge.jsonl"
  ],
  "safety": {
    "noSecrets": true,
    "noRawLogs": true,
    "noFullTranscripts": true,
    "vaultReferencesOnly": true
  }
}
