{
  "schemaVersion": "1.0",
  "kind": "agentlas-super-ontology-contract",
  "state": "export_only",
  "projectId": "{{projectId}}",
  "draftId": null,
  "runtimeGraphWriteEnabled": false,
  "zeroErrorClaim": false,
  "layers": [
    "source_intake",
    "evidence_packet",
    "belief_ledger",
    "knowledge_capsule",
    "affordance_action_binding",
    "open_world_coverage_contract",
    "consensus_coordination_contract",
    "task_coverage_contract",
    "contextual_flow_contract",
    "causal_impact_contract",
    "assurance_case_contract",
    "knowledge_homeostasis_contract",
    "adversarial_provenance_contract",
    "epistemic_calibration_contract",
    "semantic_alignment_contract",
    "resilience_control_contract",
    "invariant_verification_contract",
    "observability_telemetry_contract",
    "objective_proxy_validity_contract",
    "stakeholder_preference_governance_contract",
    "normative_authority_drift_contract",
    "side_effect_containment_contract",
    "agentlas_integration_contract",
    "memory_curator_bridge",
    "promotion_readiness",
    "promotion_replay_drill",
    "architecture_sync_review"
  ],
  "evidenceLedgers": {
    "replays": ".agentlas/super-ontology-replays.jsonl",
    "promotionEvidence": ".agentlas/super-ontology-evidence.jsonl",
    "openWorldCoverage": ".agentlas/super-ontology-open-world-coverage.json",
    "consensusCoordination": ".agentlas/super-ontology-consensus-coordination.json",
    "taskCoverage": ".agentlas/super-ontology-task-coverage.json",
    "contextualFlow": ".agentlas/super-ontology-contextual-flow.json",
    "causalImpact": ".agentlas/super-ontology-causal-impact.json",
    "assuranceCase": ".agentlas/super-ontology-assurance-case.json",
    "knowledgeHomeostasis": ".agentlas/super-ontology-knowledge-homeostasis.json",
    "adversarialProvenance": ".agentlas/super-ontology-adversarial-provenance.json",
    "epistemicCalibration": ".agentlas/super-ontology-epistemic-calibration.json",
    "semanticAlignment": ".agentlas/super-ontology-semantic-alignment.json",
    "resilienceControl": ".agentlas/super-ontology-resilience-control.json",
    "invariantVerification": ".agentlas/super-ontology-invariant-verification.json",
    "observabilityTelemetry": ".agentlas/super-ontology-observability-telemetry.json",
    "objectiveProxyValidity": ".agentlas/super-ontology-objective-proxy-validity.json",
    "stakeholderPreferenceGovernance": ".agentlas/super-ontology-stakeholder-preference-governance.json",
    "normativeAuthorityDrift": ".agentlas/super-ontology-normative-authority-drift.json",
    "sideEffectContainment": ".agentlas/super-ontology-side-effect-containment.json",
    "memoryCuratorBridge": ".agentlas/super-ontology-memory-bridge.jsonl",
    "memoryTickets": ".agentlas/memory-tickets.jsonl"
  },
  "hardStops": [
    "zero_error_claim",
    "raw_source_to_graph_write",
    "forbidden_context_join",
    "whole_graph_exposure",
    "tool_authority_without_provenance",
    "missing_open_world_coverage_contract",
    "proposal_example_equals_all_tasks",
    "unknown_combination_to_runtime_write",
    "untested_modality_to_memory_write",
    "implicit_degradation_as_complete_data",
    "adversarial_source_as_authority",
    "forbidden_authority_to_action",
    "missing_consensus_coordination_contract",
    "agent_agreement_as_truth",
    "majority_vote_as_write_authority",
    "debate_stability_as_proof",
    "model_judge_as_final_evidence",
    "distributed_replica_merge_without_review",
    "route_sync_without_quorum",
    "last_writer_wins_architecture_update",
    "peer_pressure_to_memory_write",
    "validator_disagreement_to_release",
    "missing_task_coverage_contract",
    "missing_contextual_flow_contract",
    "forbidden_context_flow",
    "missing_causal_impact_contract",
    "correlation_as_causation",
    "missing_assurance_case_contract",
    "unsupported_claim",
    "missing_knowledge_homeostasis_contract",
    "error_budget_overrun_continues",
    "critical_homeostasis_runtime_write",
    "privacy_incident_public_export",
    "missing_adversarial_provenance_contract",
    "prompt_injection_as_instruction",
    "forged_provenance_as_trusted_source",
    "poisoned_source_to_memory",
    "tool_output_tampering_to_action",
    "stale_trusted_source_replay_as_current_truth",
    "missing_epistemic_calibration_contract",
    "uncalibrated_confidence_to_answer",
    "unknown_state_to_runtime_write",
    "conflicting_sources_as_current_truth",
    "low_retrieval_relevance_as_confident_answer",
    "wide_judge_interval_to_regulated_answer",
    "missing_semantic_alignment_contract",
    "same_label_as_same_meaning",
    "embedding_similarity_as_exact_match",
    "close_match_as_transitive_truth",
    "generated_label_as_ontology_class",
    "appbridge_route_as_source_ontology_edit",
    "same_individual_without_stable_identifier",
    "unit_label_without_unit_compatibility",
    "source_conflict_to_memory_merge",
    "no_match_promoted_to_weak_match",
    "missing_resilience_control_contract",
    "validator_disagreement_to_graph_write",
    "retrieval_drift_to_current_answer",
    "semantic_regression_to_memory_merge",
    "curator_backlog_to_direct_memory_write",
    "tool_error_spike_to_unbounded_retry",
    "sync_drift_to_release_surface",
    "degraded_parser_to_ontology_class",
    "emergency_stop_bypass_by_route",
    "missing_invariant_verification_contract",
    "memory_write_without_ticket_invariant",
    "graph_write_without_evidence_invariant",
    "tool_action_without_authority_invariant",
    "public_export_without_flow_invariant",
    "route_sync_without_source_contract_invariant",
    "rollback_not_observed_after_violation",
    "emergency_stop_transition_bypassed",
    "unordered_multi_agent_write",
    "non_idempotent_replay_mutation",
    "missing_observability_telemetry_contract",
    "write_without_trace_id",
    "memory_ticket_without_span_lineage",
    "tool_action_without_audit_receipt",
    "public_export_with_stale_metric",
    "route_sync_without_correlation_id",
    "release_seed_when_audit_sink_down",
    "redaction_missing_in_telemetry",
    "metric_green_without_sample_size",
    "alert_suppressed_during_degraded_mode",
    "shadow_replay_not_recorded",
    "repair_without_before_after_snapshot",
    "rollback_without_observed_event",
    "unobservable_runtime_write",
    "missing_objective_proxy_validity_contract",
    "metric_improvement_as_goal_completion",
    "approval_rate_as_trust",
    "benchmark_score_as_reliability",
    "test_pass_rate_as_maintainability",
    "open_rate_as_customer_value",
    "self_judge_score_as_truth",
    "edge_count_as_knowledge_quality",
    "short_term_profit_as_compliance",
    "cost_per_execution_as_sustainability",
    "reward_score_as_quality",
    "label_leakage_as_accuracy",
    "green_dashboard_as_health",
    "proxy_optimization_without_countermetric",
    "optimization_without_stakeholder_map",
    "metric_gaming_without_probe",
    "reward_tampering_to_promotion",
    "construct_underdefined_to_runtime_write",
    "unvalidated_proxy_to_public_release",
    "missing_stakeholder_preference_governance_contract",
    "single_stakeholder_preference_as_global_goal",
    "owner_preference_as_all_stakeholders",
    "majority_preference_as_rights_clearance",
    "average_utility_over_protected_constraint",
    "hidden_affected_party",
    "missing_appeal_path",
    "missing_dissent_capture",
    "strategic_preference_report_as_truth",
    "preference_aggregation_without_rule",
    "preference_conflict_to_runtime_write",
    "consent_absent_to_personalization",
    "minority_harm_hidden_by_aggregate",
    "irreversible_action_without_stakeholder_review",
    "private_preference_to_public_release",
    "cross_context_preference_reuse_without_scope",
    "role_power_as_legitimacy",
    "arrow_impossibility_ignored",
    "manipulable_vote_as_stable_preference",
    "stakeholder_map_missing_for_release",
    "missing_normative_authority_drift_contract",
    "stale_policy_as_current_rule",
    "wrong_jurisdiction_as_valid_policy",
    "draft_policy_as_enforced_rule",
    "superseded_contract_as_current_authority",
    "terms_of_service_without_effective_date",
    "local_custom_as_global_policy",
    "internal_preference_as_legal_requirement",
    "policy_exception_without_owner",
    "conflicting_authorities_without_precedence",
    "regulation_summary_as_primary_law",
    "compliance_claim_without_citation",
    "policy_translation_as_authoritative_text",
    "expired_consent_as_current_permission",
    "missing_retention_or_deletion_rule",
    "cross_border_transfer_without_jurisdiction",
    "licensing_constraint_ignored",
    "audit_requirement_missing_before_release",
    "emergency_exception_without_expiry",
    "legal_advice_without_review",
    "missing_side_effect_containment_contract",
    "read_permission_as_write_permission",
    "preview_as_send",
    "dry_run_result_as_committed",
    "non_idempotent_retry_to_external_action",
    "irreversible_action_without_human_approval",
    "deletion_without_recovery_plan",
    "payment_without_idempotency_key",
    "customer_message_without_review",
    "release_without_rollback",
    "connector_write_without_scope",
    "cross_tool_chain_without_transaction",
    "compensation_plan_missing",
    "blast_radius_unknown",
    "idempotency_key_missing",
    "external_commit_without_receipt",
    "partial_failure_without_saga_state",
    "physical_action_without_safety_interlock",
    "scheduled_action_without_cancellation",
    "side_effect_logging_missing",
    "hosted_tool_without_local_side_effect_wrapper",
    "appbridge_source_of_truth_write",
    "direct_durable_memory_write",
    "raw_prompt_or_secret_memory_capture",
    "missing_memory_curator_bridge",
    "missing_rollback",
    "missing_shadow_or_canary_evidence"
  ],
  "promotionPolicy": {
    "shadowRequired": true,
    "canaryRequiredForMixedContext": true,
    "rollbackRequired": true,
    "syncReviewRequired": true,
    "openWorldCoverageRequired": true,
    "unknownCombinationRuntimeWritesBlocked": true,
    "uncoveredModalityRuntimeWritesBlocked": true,
    "consensusCoordinationRequired": true,
    "agentAgreementRuntimeWritesBlocked": true,
    "majorityVoteRuntimeWritesBlocked": true,
    "splitBrainRuntimeWritesBlocked": true,
    "taskCoverageRequired": true,
    "contextualFlowRequired": true,
    "causalImpactRequired": true,
    "assuranceCaseRequired": true,
    "knowledgeHomeostasisRequired": true,
    "adversarialProvenanceRequired": true,
    "untrustedSourceRuntimeWritesBlocked": true,
    "epistemicCalibrationRequired": true,
    "uncalibratedRuntimeWritesBlocked": true,
    "semanticAlignmentRequired": true,
    "highAuthorityAlignmentReviewRequired": true,
    "unreviewedSemanticRuntimeWritesBlocked": true,
    "resilienceControlRequired": true,
    "degradedRuntimeWritesBlocked": true,
    "emergencyStopBypassBlocked": true,
    "invariantVerificationRequired": true,
    "runtimeInvariantWritesBlocked": true,
    "forbiddenTransitionBlocked": true,
    "observabilityTelemetryRequired": true,
    "unobservableRuntimeWritesBlocked": true,
    "auditSinkRequired": true,
    "crossSurfaceCorrelationRequired": true,
    "objectiveProxyValidityRequired": true,
    "proxyOptimizationRuntimeWritesBlocked": true,
    "countermetricRequired": true,
    "metricGamingProbeRequired": true,
    "stakeholderPreferenceGovernanceRequired": true,
    "singleStakeholderRuntimeWritesBlocked": true,
    "aggregationRuleRequired": true,
    "appealPathRequired": true,
    "normativeAuthorityDriftRequired": true,
    "stalePolicyRuntimeWritesBlocked": true,
    "jurisdictionScopeRequired": true,
    "authorityHierarchyRequired": true,
    "sideEffectContainmentRequired": true,
    "irreversibleRuntimeActionsBlocked": true,
    "idempotencyKeyRequired": true,
    "compensationPlanRequired": true,
    "memoryCuratorBridgeRequired": true,
    "directDurableMemoryWritesBlocked": true,
    "appbridgeSourceWritesBlocked": true
  },
  "surfacePolicy": {
    "publicResearchRepo": {
      "defaultDecision": "candidate_only",
      "notes": "Research artifacts may be validated and inspected."
    },
    "publicCore": {
      "defaultDecision": "sync_review_required",
      "notes": "Only public-safe contracts may be mirrored."
    },
    "webRuntime": {
      "defaultDecision": "shadow_required",
      "notes": "Hosted ZIP/export behavior needs shadow replay before promotion."
    },
    "desktopTerminal": {
      "defaultDecision": "shadow_required",
      "notes": "Local seed/runtime behavior needs permission audit and replay."
    },
    "appbridge": {
      "defaultDecision": "blocked",
      "notes": "AppBridge remains a route adapter, never the source of truth."
    }
  }
}
